Repository cloud-native-toolkit/image-cli-tools-web-terminal, pull requests merged in 2022-08, with the labels that each got.

#3 Adds banner text to entrypoint
  .github/workflows/docker-build.yaml
  entrypoint.sh
Labels: feature, minor

#4 Fixes container repo name
  .github/workflows/docker-build.yaml
Labels: bug, patch

#8 Adds .bashrc and .bash_profile files
  .bash_profile
  .bashrc
  Containerfile
  entrypoint.sh
Labels: feature, minor

#18 Adds README file
  .github/workflows/docker-build.yaml
  README.md
Labels: feature, minor

#19 Bumps version of base images to latest
  .github/workflows/docker-build.yaml
Labels: bug, patch

#20 Adds workflow to update build workflow when new versions released
  .github/workflows/docker-build.yaml
  .github/workflows/update-base-image.yaml
Labels: bug, chore, patch

#21 Updates workflow to update base image
  .github/workflows/update-base-image.yaml
Labels: chore, patch

#22 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.3
  .github/workflows/docker-build.yaml
Labels: bug, patch

#23 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.4.7
  .github/workflows/docker-build.yaml
Labels: bug, patch

#24 Updates cloud-native-toolkit/image-cli-tools module to v2.2.3
  .github/workflows/docker-build.yaml
Labels: bug, patch

#25 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.4
  .github/workflows/docker-build.yaml
Labels: bug, patch

#26 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.4.8
  .github/workflows/docker-build.yaml
Labels: bug, patch

#27 Updates cloud-native-toolkit/image-cli-tools module to v2.2.4
  .github/workflows/docker-build.yaml
Labels: bug, patch

#28 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.5
  .github/workflows/docker-build.yaml
Labels: bug, patch

#29 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.4.9
  .github/workflows/docker-build.yaml
Labels: bug, patch

#30 Updates cloud-native-toolkit/image-cli-tools module to v2.2.5
  .github/workflows/docker-build.yaml
Labels: bug, patch

#31 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.6
  .github/workflows/docker-build.yaml
Labels: bug, patch

#32 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.4.10
  .github/workflows/docker-build.yaml
Labels: bug, patch

#33 Updates cloud-native-toolkit/image-cli-tools module to v2.2.6
  .github/workflows/docker-build.yaml
Labels: bug, patch
