Repository cloud-native-toolkit/image-cli-tools-web-terminal, pull requests merged in 2025-03, with the labels that each got.

#74 Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.0
  .github/workflows/docker-build.yaml
Labels: feature, minor

#76 Updates cloud-native-toolkit/image-cli-tools module to v3.0.0
  .github/workflows/docker-build.yaml
Labels: feature, minor

#77 Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.2
  .github/workflows/docker-build.yaml
Labels: bug, patch

#78 Updates cloud-native-toolkit/image-cli-tools module to v3.0.1
  .github/workflows/docker-build.yaml
Labels: bug, patch

#79 Updates cloud-native-toolkit/image-cli-tools module to v3.0.2
  .github/workflows/docker-build.yaml
Labels: bug, patch

#80 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.8.3
  .github/workflows/docker-build.yaml
Labels: bug, patch

#81 Update workflow config
  .github/workflows/docker-build.yaml
Labels: chore, patch

#83 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.8.4
  .github/workflows/docker-build.yaml
Labels: bug, patch

#84 Updates cloud-native-toolkit/image-cli-tools module to v3.0.3
  .github/workflows/docker-build.yaml
Labels: bug, patch
